services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www/html
            - ./_docker/nginx/logs/nginx:/var/log/nginx
            - ./_docker/socket:/socket
        container_name: pizza_nginx
        depends_on:
            - app

    app:
        build:
            context: ../pizza/_docker/app
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./_docker/socket:/socket
            - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=docker-server"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9003:9003"
        container_name: pizza_app
        depends_on:
            - db

    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        container_name: pizza_db

volumes:
    postgres_data:
        driver: local
